<?php
$title = 'Adicionar Contato';
$this->headTitle($title);
?>
    <div class="panel">
        <h2><?php echo sprintf($this->translate('%s' . $title . '%s'), '<span class="zf-green">', '</span>') ?></h2>
        <?php
            $form = $this->form;
            $form->setAttribute('action', $this->url('contato', array('action' => 'add')));
            $form->prepare();
            echo $this->form()->openTag($form);
            echo $this->formHidden($form->get('id'));
            echo $this->formRow($form->get('nome'));
            echo $this->formRow($form->get('empresa'));
            echo $this->formSubmit($form->get('submit'));
            echo $this->form()->closeTag();
        ?>
    </div>