<?php
$title = 'Meus Contatos';
$this->headTitle($title);
?>

    <div class="panel">
        <h2><?php echo sprintf($this->translate('%s'.$title.'%s'), '<span class="zf-green">', '</span>') ?></h2>
        <p><a class="btn btn-default btn-small" href="<?php echo $this->url('contato', array('action'=>'add'));?>"><?php echo $this->translate('Adicionar novo contato') ?></a></p>
        
        <table class="table table-bordered  ">
            <tr>
                <th>Nome</th>
                <th>Empresa</th>
                <th>&nbsp;</th>
            </tr>
            <?php foreach ($this->contatos as $contato) : ?>
            <tr>
                <td><?php echo $this->escapeHtml($contato->getNome());?></td>
                <td><?php echo $this->escapeHtml($contato->getEmpresa());?></td>
                <td>
                    <a class="btn btn-default btn-small" href="<?php echo $this->url('contato',array('action'=>'edit', 'id' => $contato->getId()));?>"><?php echo $this->translate('Editar contato') ?></a>
                    <a class="btn btn-default btn-small" href="<?php echo $this->url('contato',array('action'=>'delete', 'id' => $contato->getId()));?>"><?php echo $this->translate('Excluir contato') ?></a>
                </td>
            </tr>
            <?php endforeach; ?>
        </table>
    </div>